application: arduinoproxy
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /main.css
  static_files: static/main.css
  upload: static/main.css

- url: .*
  script: main.py


